= Integratieproject 1 | 2024-2025

== Team 14

== Inspraak portaal XIV [IP14]

Op ons platform *IP14* kan een organisatie, gemeenschap, club, of eender wie anders, een account aanmaken. Hiermee kunt u *panels hosten*.
Ons platform is vooral gemaakt voor het aanmaken van *burgerpanels*, maar kan ook gebruikt worden voor kleinere panels.
We bieden u een tool om uw panel samen te stellen. U kunt mensen uitnodigen op basis van verschillende criteria.
Wanneer de uitgenodigde beslissen deel te nemen aan uw panel, zal u via ons een *projectpagina* kunnen samenstellen waar u posts kunt maken en kunt communiceren met het panel.
U kunt hier vergaderingen inplannen en stemming houden.

=== Ons team
* link:https://www.linkedin.com/in/ilja-nachtergaele-8665b622a/[Ilja Nachtergaele]
* link:https://www.linkedin.com/in/stijn-similon-b86a27332/[Stijn Similon]
* link:https://www.linkedin.com/in/tibo-eycken-b81aaa1a3/[Tibo Eycken]
* link:https://www.linkedin.com/in/zachary-van-de-staey-04ba56229/[Zachary Van De Staey]

== Deployment Scripts - Google Compute Engine (GCE)

Dit project bevat bash-scripts voor het automatisch opzetten, beheren en verwijderen van een volledige infrastructuur op *Google Compute Engine (GCE)*.

== Functionaliteiten

=== Vereist

- Opzetten van de volledige omgeving
- Volledig verwijderen van de omgeving
- Deployen van een nieuwe versie (upgrade)

=== Extra's

- Backup en restore van de database
- Monitoring met Ops Agent
- Custom domeinnaam
- Zero-downtime deployment (Zie CI-CD in .NET applicatie)

== Vereisten

Zorg ervoor dat volgende tools geïnstalleerd zijn:

- *Bash* (4.0+) https://git-scm.com/downloads[Installatie Git Bash]
- *Google Cloud SDK (gcloud)* – https://cloud.google.com/sdk/docs/install[Installatie]
- *curl* – Voor API-aanroepen https://curl.haxx.se/[Installatie]
- Een actief *Google Cloud-account* met voldoende rechten https://cloud.google.com/?hl=en[Google Cloud]

== Voorbereiding

=== Inloggen bij gcloud

1. Open een terminal en gebruik `gcloud auth login`
2. Volg de gevraagde stappen

=== Billing account

Ga naar https://console.cloud.google.com/billing[console.cloud.google.com > billing] > Create account, geef een naam en link aan een payment profiel of maak een nieuw profiel.

Bewaar deze *Billing Account ID*.

=== Toevoegen Secrets

Maak een nieuw bestand met de naam `secrets.sh` in de map `secrets`.

Plak onderstaande inhoud in het bestand:

[source,bash]
----
#!/bin/bash

# --- Cloud SQL ---
CLOUD_SQL_PASSWORD=""
CLOUD_SQL_USER=""

# --- Billing Account ---
BILLING_ACCOUNT_ID=""

# --- Sendgrid API Keys ---
SENDGRID_API_KEY=""

# --- provincies-in-cijfers Keys ---
PINC_API_KEY=""

# --- Application Bucket Name ---
APP_BUCKET=""

# --- Cloudflare API Token ---
CLOUDFLARE_API_TOKEN=""
CLOUDFLARE_ZONE_ID=""

# --- Gitlab Keys ---
GITLAB_TOKEN=""
GITLAB_PROJECT_ID=""
----

Te kiezen: een *CLOUD_SQL_PASSWORD*, *CLOUD_SQL_USER* en *APP_BUCKET*. Plak hier ook het verkregen *BILLING_ACCOUNT_ID*.

=== Stappen Domeinnaam + SSL

==== 1. API key voor Cloudflare

- Vraag een domeinnaam aan via een provider.
- In Cloudflare: profiel > API Tokens > Create Token > Edit zone DNS
- Selecteer je domein en kopieer de gegenereerde token naar `CLOUDFLARE_API_TOKEN` in `secrets.sh`.

==== 2. Cloudflare Zone ID

- Ga naar je domein in Cloudflare
- Scroll naar beneden en kopieer de *Zone ID* naar `CLOUDFLARE_ZONE_ID`

==== 3. Installeren SSL certificaat

- Cloudflare > SSL/TLS > Origin Server > Create Certificate
- Voeg je domein en `*.domein` toe
- Kopieer certificaat naar `cf-cert.pem`, private key naar `cf-key.pem` in de `secrets/` map

==== 4. PINC API

- Mail naar `info@provincies.incijfers.be` en voeg ontvangen API key toe aan `PINC_API_KEY`.

=== API key Sendgrid

- Maak account aan op https://www.sendgrid.com/
- Ga naar API Key Management
- Voeg toe aan `SENDGRID_API_KEY` in `secrets.sh`

=== GitLab Personal Access Token

1. Ga naar https://gitlab.com/-/profile/personal_access_tokens
2. Geef naam, vervaldatum en scope `api`
3. Voeg token toe aan `GITLAB_TOKEN` in `secrets.sh`

=== GitLab project ID

1. Ga naar je repo > Settings > General
2. Kopieer Project ID en voeg toe aan `GITLAB_PROJECT_ID`

== Projectstructuur

[source,bash]
----
scripts/
├── modules/                          
│   ├── add_lb_ip_to-cloudflare.sh
│   ├── colors.sh                         
│   ├── config.sh  
│   ├── create_ssl_cert.sh
│   ├── pre_deploy_checks.sh
│   ├── setup_bucket.sh
│   ├── setup_health_checks.sh
│   ├── setup_load_balancer.sh
│   ├── setup_managed_instance_group.sh
│   ├── setup_project_variables.sh
│   ├── setup_redis_instance.sh
│   ├── setup_sql_database.sh
│   └── setup_vpc_network.sh
│
├── secrets/
│   ├── secrets.sh                        
│   ├── cf-cert.pem
│   ├── cf-key.pem                           
│
├── vmScripts/                        
│   ├── startup-script.sh            
│
├── .gitignore                        
├── delete_project.sh                 
├── deploy_using_modules.sh          
├── destroy.sh                        
├── initial_setup_script.sh         
├── restore_cloud_sql_backup.sh      
├── upgrade_current_code.sh         
README.md            
README.adoc            
----

== Configuratie

Pas onderstaande variabelen aan in `modules/config.sh`:

[source,bash]
----
PROJECT_ID=""                # Moet uniek zijn (bijv. ons-eerste-project-1a)
PROJECT_NAME=""              # Kies een naam naar keuze
ZONE="europe-west1-b"        # Laat zo of wijzig met `gcloud compute zones list`
REGION="europe-west1"        # Laat zo of wijzig met `gcloud compute regions list`
----

== Aanpassen `startup-script.sh`

Vervang deze variabelen:

[source,bash]
----
# Variables
GIT_REPO=""              # Repo-URL
GIT_BRANCH=""            # Branch naam
DOMAIN_NAME=""           # Je domeinnaam
----

== Scripts gebruiken

=== Alles opzetten + deployen

Als je heel de google cloud infrastructuur wilt opzetten en je applicatie wilt deployen gebruik dan
[source,bash]
----
./initial_setup_script.sh
----

=== Alleen deployen

Stel je hebt je google cloud omgeving al opgezet dan kun je ook enkel deployen met
[source,bash]
----
./deploy_using_modules.sh deploy
----

=== Backup restoren

Als je je databank wilt terugdraaien naar een backup gebruik dan 
[source,bash]
----
./restore_cloud_sql_backup.sh
----

=== Code upgraden

Stel dat er een update in de code is gebeurt en je wilt deze op je instanties krijgen gebruik dan 
[source,bash]
----
./upgrade_current_code.sh
----

=== Deployment verwijderen

Als je je deployment offline wilt halen kan dit met 
[source,bash]
----
./destroy.sh
----

=== Google Project verwijderen

Als je heel je google cloud project wilt verwijderen gebruik dan 
[source,bash]
----
./delete_project.sh
----

== Veelvoorkomende problemen

=== ERROR: Cannot delete an inactive project

*Oorzaak:* Het project is al gemarkeerd voor verwijdering of je hebt geen rechten.  
*Oplossing:* Controleer met:

[source,bash]
----
gcloud projects describe $PROJECT_ID
----

=== API access denied

*Oorzaak:* Ontbrekende of foutieve API keys.  
*Oplossing:* Controleer `secrets.sh`.

== Schatting Maandelijkse Kost

[cols="2,5,1,2,2,2,2"]
|===
| service_display_name | name | quantity | region | service_id | sku | total_price_EUR

| Secret Manager
| Secret version replica storage
| 10
| global
| EE82-7A5E-775C
| 7756-ADEF
| 0.21118

| VMs (Compute Engine)
| E2 Instance:Core running in EMEA
| 1460
| europe-west2
| 6F81-5844-46A
| 9FE0-8F60
| 30.8232

| VMs (Compute Engine)
| E2 Instance:Ram running in EMEA
| 5840
| europe-west2
| 6F81-5844-46A
| F268-6CE7
| 16.52625

| VMs (Compute Engine)
| Balanced PD Capacity
| 20
| europe-west2
| 6F81-5844-46A
| 6AE1-525F
| 1.7598

| PostgreSQL (Cloud SQL)
| Cloud SQL for PostgreSQL Zonal - IOPS in EMEA
| 1460
| europe-west2
| 9662-B51E-5089
| 2154-E036
| 53.05621

| PostgreSQL (Cloud SQL)
| Cloud SQL for PostgreSQL Zonal - RAM in EMEA
| 5475
| europe-west2
| 9662-B51E-5089
| 8A88-5E4E
| 33.72217

| PostgreSQL (Cloud SQL)
| Cloud SQL for PostgreSQL Zonal - Standard storage in EMEA
| 73000
| europe-west2
| 9662-B51E-5089
| B14E-2B60
| 13.931

| Redis (Cloud Memorystore)
| Redis Capacity Basic M2 Belgium
| 7300
| europe-west2
| 5AF5-2C11-0467
| AC1B-F435
| 205.5446

| Static IP (Networking)
| External IP Charge on a Standard VM
| 1
| global
| 6F81-5844-46A
| C054-7F72
| 0

| Static IP (Networking)
| External IP Charge on a Spot/Preemptible VM
| 0
| global
| 6F81-5844-46A
| 4AF8-7C1F
| 0

| Static IP (Networking)
| Static Ip Charge
| 0
| europe-west2
| 6F81-5844-46A
| 66A2-68EA
| 0

| Load Balancer (Networking)
| Regional External Application Load Balancer Inbound Data Processing for Belgium (europe-west1)
| 100
| europe-west2
| E505-509A-58F9
| 4CA1-8FBD
| 0.70392

| Load Balancer (Networking)
| Regional External Application Load Balancer Outbound Data Processing for Belgium (europe-west1)
| 100
| europe-west2
| E505-509A-58F9
| 6447-DBD0
| 0.70392

| Load Balancer (Networking)
| Regional External Proxy Network Load Balancer Forwarding Rule Minimum for Belgium (europe-west1)
| 1
| europe-west2
| E505-509A-58F9
| A1EB-4344
| 16.05818

| Bucket (Cloud Storage)
| Standard Storage Belgium
| 100
| europe-west2
| 95FF-2EF5-5541
| A703-5CB6
| 1.7598

| *Total Price:*
|
|
|
|
|
| *374.8002*
|===

Deze prijzen zijn een *schatting* in EURO, verkregen op *27/05/2025* via de Google Cloud Service 'Cost Estimation'.

Om kosten te drukken of performantie te verhogen kunnen wijzigingen aangebracht worden in het configuratiebestand. Om zelf aanpassingen en bijhorende kosten te kunnen bekijken gebruik dan link:https://cloud.google.com/products/calculator[Google Cloud Cost Estimation].

== Auteur

Deze scripts werden geschreven door *Tibo Eycken* in het kader van het IP1-project aan *KdG*.
